/**
 * @packageDocumentation
 * @module api.functional
 * @nestia Generated by Nestia - https://github.com/samchon/nestia 
 */
//================================================================
import type { IConnection } from "@nestia/fetcher";
import { PlainFetcher } from "@nestia/fetcher/lib/PlainFetcher";

/**
 * @controller AppController.check
 * @path GET /
 * @nestia Generated by Nestia - https://github.com/samchon/nestia
 */
export async function check(
    connection: IConnection,
): Promise<void> {
    return PlainFetcher.fetch(
        connection,
        {
            ...check.METADATA,
            path: check.path(),
        } as const,
    );
}
export namespace check {

    export const METADATA = {
        method: "GET",
        path: "/",
        request: null,
        response: {
            type: "application/json",
            encrypted: false,
        },
        status: null,
    } as const;

    export const path = (): string => {
        return `/`;
    }
}